# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TranswideLogisticsUser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


 
   pod 'Cosmos'
   pod 'MBProgressHUD'
   pod 'SDWebImage'
   pod 'SwiftyJSON'
   pod 'IQKeyboardManagerSwift'
   pod 'Firebase/Auth'
   pod 'Firebase/Core'
   pod 'Firebase/Firestore'
   pod 'Firebase/Analytics'
   pod 'Firebase/Messaging'
   pod 'FacebookCore'
   pod 'FacebookLogin'
   pod 'FBSDKCoreKit'
   pod 'FBSDKLoginKit'
   pod 'GoogleSignIn'
   pod 'GoogleMaps'
   pod 'GooglePlaces'

  # Pods for TranswideLogisticsUser

  target 'TranswideLogisticsUserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TranswideLogisticsUserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
